name: Release

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    name: Build and Release
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - os: linux
            arch: amd64
            name: linux-amd64
          - os: linux
            arch: arm64
            name: linux-arm64
          - os: darwin
            arch: amd64
            name: darwin-amd64
          - os: darwin
            arch: arm64
            name: darwin-arm64

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.25"

      - name: Build binary
        run: |
          CGO_ENABLED=0 GOOS=${{ matrix.os }} GOARCH=${{ matrix.arch }} go build \
            -ldflags="-s -w" \
            -trimpath \
            -o clai-${{ matrix.name }} \
            main.go

      - name: Make executable
        run: chmod +x clai-${{ matrix.name }}

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: clai-${{ matrix.name }}
          path: clai-${{ matrix.name }}

  release:
    name: Create Release
    needs: build
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v')

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download all build artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts/

      - name: Prepare release assets
        run: |
          mkdir -p release-assets
          cd artifacts/
          find . -name "clai-*" -type f -exec cp {} ../release-assets/ \;
          cd ../release-assets
          ls -la

      - name: Generate changelog
        id: changelog
        run: |
          # Get the latest tag
          LATEST_TAG=$(git describe --tags --abbrev=0 2>/dev/null || echo "")

          # Get commits since last tag
          if [ -n "$LATEST_TAG" ]; then
            CHANGES=$(git log --pretty=format:"* %s (%h)" "${LATEST_TAG}..HEAD" 2>/dev/null || echo "* Initial release")
          else
            CHANGES="* Initial release"
          fi

          echo "changes<<EOF" >> $GITHUB_OUTPUT
          echo "$CHANGES" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          body: |
            ## Changes

            ${{ steps.changelog.outputs.changes }}

            ## Downloads

            Download the appropriate binary for your platform from the assets below.

            **Installation:**
            ```bash
            # Linux/macOS - Download and install
            wget https://github.com/samanar/clai/releases/download/${{ github.ref_name }}/clai-<platform>
            chmod +x clai-<platform>
            sudo mv clai-<platform> /usr/local/bin/clai
            ```

            **Supported Platforms:**
            - Linux (amd64, arm64)
            - macOS (amd64, arm64)

            **Note:** On first run, CLAI will download the necessary AI models (~1.3-3.5 GB depending on your selection).
          draft: false
          prerelease: false
          files: ./release-assets/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
